### ISSUE TITLE
plugin assumes that GPT can do the lookup from label to ID

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/oai-monarch-plugin#1]
<img width="1001" alt="image" src="https://github.com/monarch-initiative/oai-monarch-plugin/assets/50745/7d6c0942-d7e7-4c39-b7d7-f003db99faa0">

this was added in June last year:

```yaml
id: MONDO:0007981
name: metachromatic leukodystrophy, adult-onset, with normal arylsulfatase A
comment: Reason of obsoletion: out of scope - MONDO:excludeHistoricalDisease. Term to consider: -none
subset: obsoletion_candidate
synonym: "metachromatic leukodystrophy, adult-onset, with normal arylsulfatase A" EXACT [OMIM:156310]
synonym: "metachromatic leukodystrophy, adult-onset, with normal arylsulfatase type A" EXACT [MONDORULE:1, OMIM:156310]
xref: MESH:C563587 {source="MONDO:equivalentTo"}
xref: OMIM:156310 {source="MONDO:equivalentTo"}
xref: Orphanet:512 {source="OMIM:156310"}
xref: UMLS:C1835007 {source="MONDO:equivalentTo", source="OMIM:156310", source="MONDO:ncbi_mim2gene_medline"}
is_a: MONDO:0019255 {source="https://clinicalgenome.org/affiliation/50009/"} ! sphingolipidosis
relationship: excluded_subClassOf MONDO:0018868 {source="MESH:C563587", source="Orphanet:512/btnt"} ! metachromatic leukodystrophy
property_value: confidence "0.0" xsd:double
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/6019" xsd:anyURI
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/6055" xsd:anyURI
property_value: IAO:0006012 "2023-06-01" xsd:string
```

looking at the API log it seems that ChatGPT doesn't even try to access the API. It "knows" that it needs to convert the label to an ID, and it knows it can't do that here.

we can experiment with either

- a name to ID route, and hope it knows how to chain
- allowing label to be used in association queries (a bit ugly...)
